'use strict';

const CONSTANTS = {
  // Roles
  ROLE_USER: 0,
  ROLE_ADMIN: 1,
  ROLE_DEV: 2,

  // Tipos de usuario en huertos
  TYPE_WAIT_LIST: 0,
  TYPE_MEMBER: 1,
  TYPE_WITH_GREENHOUSE: 2,
  TYPE_COLLABORATOR: 3,
  TYPE_DEVELOPER: 4,
  TYPE_SUBSIDY: 5,

  // Estado de usuario
  STATUS_INACTIVE: 0,
  STATUS_ACTIVE: 1,

  // Tipos de solicitud
  REQUEST_TYPE_REGISTER: 0,
  REQUEST_TYPE_UNREGISTER: 1,
  REQUEST_TYPE_ADD_COLLABORATOR: 2,
  REQUEST_TYPE_REMOVE_COLLABORATOR: 3,
  REQUEST_TYPE_ADD_GREENHOUSE: 4,
  REQUEST_TYPE_REMOVE_GREENHOUSE: 5,

  // Estado de solicitud
  REQUEST_PENDING: 0,
  REQUEST_APPROVED: 1,
  REQUEST_REJECTED: 2,

  // Tipo de pago
  PAYMENT_TYPE_BANK: 0,
  PAYMENT_TYPE_CASH: 1,

  // Frecuencia de pago
  PAYMENT_FREQUENCY_BIYEARLY: 0,
  PAYMENT_FREQUENCY_YEARLY: 1,

  // Prioridad de anuncio
  ANNOUNCE_PRIORITY_LOW: 0,
  ANNOUNCE_PRIORITY_MEDIUM: 1,
  ANNOUNCE_PRIORITY_HIGH: 2,

  // Contextos
  CONTEXT_HUERTOS: 1
};

export { CONSTANTS };
